export const HeroImgSlider = [{
        id: 1,
        img: "images/mobile.png",
    },
    {
        id: 2,
        img: "images/tablet.png",
    },
    {
        id: 3,
        img: "images/laptop.png",
    },
    {
        id: 4,
        img: "images/device.png",
    },
    {
        id: 5,
        img: "images/watch.png",
    },
];
export const AllDeviceItems = [{
        id: 1,
        path: "/mobile",
        parentcls: "col-md-2",
        childcls: "item-box",
        title: "Sell Phone",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/Categories/2022/11/24/phone-removebg-preview.png",
    },
    {
        id: 2,
        path: "/tablet",
        parentcls: "col-md-2",
        childcls: "item-box",
        title: "Sell Tablet",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/Categories/2022/11/24/tab_bbk.png",
    },
    {
        id: 3,
        path: "/laptop",
        parentcls: "col-md-2",
        childcls: "item-box",
        title: "Sell Laptop",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/Categories/2022/11/24/laptop_bbk.png",
    },
    {
        id: 4,
        path: "/desktop",
        parentcls: "col-md-2",
        childcls: "item-box",
        title: "Sell Desktop",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/Categories/2022/11/24/dekstop_bbk.png",
    },
    {
        id: 5,
        path: "/watch",
        parentcls: "col-md-2",
        childcls: "item-box",
        title: "Sell Watch",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/Categories/2022/11/24/watch_bbk.png",
    },
    {
        id: 6,
        path: "/repair",
        parentcls: "col-md-2",
        childcls: "item-box",
        title: "Repair",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/Categories/2022/03/30/repair.png",
    },
];
export const SliderMobiles = [{
        id: 1,
        parentcls: "col-md-4",
        title: "iPhone 13",
        priceone: 49500,
        variantone: "128GB",
        pricetwo: 52500,
        varianttwo: "256GB",
        path: "/mobile/apple",
        sellbtn: "sell now",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/13.jpeg",

    },
    {
        id: 2,
        parentcls: "col-md-4",
        title: "iPhone 13 Pro",
        priceone: 73000,
        variantone: "128GB",
        pricetwo: 77000,
        varianttwo: "256GB",
        path: "/mobile/apple",
        sellbtn: "sell now",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/02/13PRO.jpeg",

    },
    {
        id: 3,
        parentcls: "col-md-4",
        title: "iPhone 13 Pro Max",
        priceone: 78000,
        variantone: "128GB",
        pricetwo: 84000,
        varianttwo: "256GB",
        path: "/mobile/apple",
        sellbtn: "sell now",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/iphone-13-pro-max.jpeg",

    },
    {
        id: 4,
        parentcls: "col-md-4",
        title: "OnePlus 10R",
        priceone: 24000,
        variantone: "8GB/128GB",
        pricetwo: 27000,
        varianttwo: "12GB/256GB",
        path: "/mobile/oneplus",
        sellbtn: "sell now",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/09/716uVx3Wr5L._SL1500_.jpg",

    },
    {
        id: 5,
        parentcls: "col-md-4",
        title: "MacBook Pro",
        priceone: 80000,
        variantone: "8GB/128GB",
        pricetwo: 100000,
        varianttwo: "12GB/256GB",
        path: "/laptop/apple",
        sellbtn: "sell now",
        img: "https://www.pngall.com/wp-content/uploads/2016/05/Laptop-PNG.png",

    },
    {
        id: 6,
        parentcls: "col-md-4",
        title: "Dell Vostro 3460",
        priceone: 43000,
        variantone: "6GB/128GB",
        pricetwo: 52000,
        varianttwo: "12GB/256GB",
        path: "/laptop/dell",
        sellbtn: "sell now",
        img: "https://purepng.com/public/uploads/large/purepng.com-laptoplaptoptechnologyelectronicskeyboard-112152511985990dhd.png",

    },
    {
        id: 7,
        parentcls: "col-md-4",
        title: "Panasonic",
        priceone: 24000,
        variantone: "8GB/128GB",
        pricetwo: 27000,
        varianttwo: "12GB/256GB",
        path: "/tablet/apple",
        sellbtn: "sell now",
        img: "https://pngimg.com/uploads/tablet/tablet_PNG8558.png",

    },
    {
        id: 8,
        parentcls: "col-md-4",
        title: "Redmi Note 4",
        priceone: 32000,
        variantone: "3GB/32GB",
        pricetwo: 48000,
        varianttwo: "4GB/64GB",
        path: "/mobile/mi",
        sellbtn: "sell now",
        img: "https://lh3.googleusercontent.com/proxy/frkSG-svKKnJb_UfiBqCh_rHmhFCXMdpn3q7b7LYpGmM6ATBgP0Jtnf_iMEzUoWi44a3zHjUyY5_L4rzvVhSQ308rK7M3cxM_lSudrPEcQ=s0-d",

    },
    {
        id: 9,
        parentcls: "col-md-4",
        title: "RealMe",
        priceone: 33000,
        variantone: "6GB/128GB",
        pricetwo: 45000,
        varianttwo: "12GB/256GB",
        path: "/mobile/realme",
        sellbtn: "sell now",
        img: "https://1.bp.blogspot.com/-U2rrgvIRnGU/XyfksjOEksI/AAAAAAAANgU/AuzgTJP8M7oJBD9l2ktMBotO9nVS8pxDwCLcBGAsYHQ/s1600/realme-c15.png",

    },
    {
        id: 10,
        parentcls: "col-md-4",
        title: "OnePlus 9RT",
        priceone: 32000,
        variantone: "8GB/128GB",
        pricetwo: 50000,
        varianttwo: "12GB/256GB",
        path: "/mobile/oneplus",
        sellbtn: "sell now",
        img: "https://image01.oneplus.net/shop/201711/18/122/db3a7666655eb43699750d16ddf7ec2c.png",

    },
];


/************------ Mobile Brand Pages  --------**************/
export const MobileBrandsImgs = [

    {
        id: 1,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/06/samsung.png",
        path: "/mobile/samsung",
    },
    {
        id: 2,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/25/xiaomi_1.png",
        path: "/mobile/mi",
    },
    {
        id: 3,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/25/oneplus_1.png",
        path: "/mobile/oneplus",
    },
    {
        id: 4,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/25/realme-logo-2.png",
        path: "/mobile/realme",
    },
    {
        id: 5,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/25/oppo_logo.png",
        path: "/mobile/oppo",
    },
    {
        id: 6,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/25/POCO.png",
        path: "/mobile/poco",
    },
    {
        id: 7,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/25/IQOO.png",
        path: "/mobile/iqoo",
    },
    {
        id: 8,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/25/vivo_2.png",
        path: "/mobile/vivo",
    },
    {
        id: 9,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/03/30/apple.png",
        path: "/mobile/apple",
    },
    {
        id: 10,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/09/14/Unknown.png",
        path: "/mobile/nothing",
    },
];


/************------ Tablet Brand Pages  --------**************/

export const TabletBrandsImgs = [

    {
        id: 1,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/29/apple.png",
        path: "/tablet/apple",
    },
    {
        id: 2,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/29/samsung.png",
        path: "/tablet/samsung",
    },
    {
        id: 3,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/29/lenovo.png",
        path: "/tablet/lenovo",
    },
    {
        id: 4,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/06/27/realme-logo-2.png",
        path: "/tablet/realme",
    },
    {
        id: 5,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/07/14/Xiaomi-logo.png",
        path: "/tablet/mi",
    },
];

/************------ Laptop Brand Pages  --------**************/

export const LaptopBrandsImgs = [

    {
        id: 1,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/04/06/apple.png",
        path: "/laptop/apple",
    },
    {
        id: 2,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/05/01/hp.png",
        path: "/laptop/hp",
    },
    {
        id: 3,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/05/01/acer.png",
        path: "/laptop/acer",
    },
    {
        id: 4,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/05/01/asus.png",
        path: "/laptop/asus",
    },
    {
        id: 5,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/05/01/dell.png",
        path: "/laptop/dell",
    },
    {
        id: 6,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/05/01/lenovo.png",
        path: "/laptop/lenovo",
    },
    {
        id: 7,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/06/27/xiaomi.png",
        path: "/laptop/mi",
    },
    {
        id: 8,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/06/27/realme-logo-2.png",
        path: "/laptop/realme",
    },
    {
        id: 9,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/06/27/msi_1.png",
        path: "/laptop/msi",
    },
    {
        id: 10,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/06/27/microsoft_1.png",
        path: "/laptop/microsoft",
    },

];

/*****************/
export const WatchesBrandsImgs = [

    {
        id: 1,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/brands/2022/11/10/apple.png",
        path: "/watch/apple",
    },
];



/* ----------  Samsung Mobilessssss ------------ */

export const SamsungMobiles = [


    {
        id: 1,
        title: "Galaxy S22 Ultra",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/galaxy-s22-ultra.jpg",
        variant: "12GB/512GB",
    },
    {
        id: 2,
        title: "Galaxy F23 5G",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/samsung-galaxy-f23-5g.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 3,
        title: "Galaxy M53",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/08/23/81e0KAtXRL._SL1500_.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 4,
        title: "Galaxy S9",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/S9.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 5,
        title: "Galaxy S20 Ultra",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/S20UL.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 6,
        title: "Galaxy Note 9",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/nOTE9.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 7,
        title: "Galaxy Note 8",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/NOTE8.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 8,
        title: "Galaxy M42 5G",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/galaxy-m42-5g.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 9,
        title: "Galaxy M40",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M40N.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 10,
        title: "Galaxy M32",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/galaxy-m32.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 11,
        title: "Galaxy M31",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/m31.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 12,
        title: "Galaxy M30S",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/m30s.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 13,
        title: "Galaxy M30",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/m30.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 14,
        title: "Galaxy M21",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M21.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 15,
        title: "Galaxy M20",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M20.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 16,
        title: "Galaxy M12",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M12.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 17,
        title: "Galaxy M11",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M11.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 18,
        title: "Galaxy M10S",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M10S.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 19,
        title: "Galaxy M10",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M10.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 20,
        title: "Galaxy M02S",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/galaxy-m02s.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 21,
        title: "Galaxy M01S",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/m01s.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 22,
        title: "Galaxy M01 Core",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/m01core.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 23,
        title: "Galaxy M01",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/M01.jpeg",
        variant: "",
    },
    {
        id: 24,
        title: "Galaxy J6",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/J6.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 25,
        title: "Galaxy F62",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/f62.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 26,
        title: "Galaxy F41",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/f41.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 27,
        title: "Galaxy F22",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/galaxy-f22.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 28,
        title: "Galaxy A80",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/a80.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 29,
        title: "Galaxy A72",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A72.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 30,
        title: "Galaxy A71",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A71.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 31,
        title: "Galaxy A52",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A52.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 32,
        title: "Galaxy A51",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A51.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 33,
        title: "Galaxy A50S",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A50S.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 34,
        title: "Galaxy A50",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A50.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 35,
        title: "Galaxy A5 2017",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A5_2017.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 36,
        title: "Galaxy A32",
        Brand: "Samsung",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/GALAXY_A32.jpeg",
        variant: "6GB/128GB",
    },
];


/*******  MI MOBILES   **********/
export const MIMobiles = [


    {
        id: 1,
        title: "Xiaomi Mi A3",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/XIAOMI_MI_A3.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 2,
        title: "Mi 10i 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/mi-10i.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 3,
        title: "Redmi K20",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/1642375150.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 4,
        title: "Redmi K20 Pro",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/696332671.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 5,
        title: "Redmi Note 9 Pro Max",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/REDMI_NOTE_9_PRO_MAX.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 6,
        title: "Redmi Y3",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/REDMI_Y3.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 7,
        title: "Mi 11 Lite NE 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/mi-11-lite-ne.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 8,
        title: "Mi 11 Lite",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/mi-11-lite.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 9,
        title: "Redmi 10 Prime",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/redmi-10-prime.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 10,
        title: "Xiaomi Mi 10T 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/XIAOMI_MI_10T.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 11,
        title: "Mi 12 Pro 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/26/12-pro-5g-2201122g-mi-original-imagdz78yqnz5fpt.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 12,
        title: "Xiaomi 11T Pro",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/XIAOMI_11T_PRO.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 13,
        title: "Mi 11X",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/mi-11x.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 14,
        title: "Mi 11X Pro 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/mi-11x-pro-5g.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 15,
        title: "Redmi Note 11S",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/XIAOMI_REDMI_NOTE_11S.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 16,
        title: "Redmi Note 10",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/2078137352.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 17,
        title: "Redmi Note 10S",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/redmi-note-10s.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 18,
        title: "Redmi Note 10 Lite",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/redmi-note-10-lite.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 19,
        title: "Redmi Note 10T 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/redmi-note-10t-5g.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 20,
        title: "Redmi Note 10 Pro Max",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/1939375574.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 21,
        title: "Redmi Note 10 Pro",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/1721807681.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 22,
        title: "Redmi 8A",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/466965662.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 23,
        title: "Redmi 8",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/482158939.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 24,
        title: "Redmi 8A Dual",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/1816261586.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 25,
        title: "Redmi Note 6 Pro",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/600800775.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 26,
        title: "Redmi 10A",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/10/23/71293gyogZL._SL1500_.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 27,
        title: "Redmi Note 7S",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/1412867589.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 28,
        title: "Redmi Note 7",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/1252475561.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 29,
        title: " Redmi Note 7 Pro",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/519558852.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 30,
        title: "Redmi Note 8 Pro",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/REDMI_NOTE_8_PRO.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 31,
        title: "Redmi Note 8",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/1861030312.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 32,
        title: "Redmi Note 9",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/REDMI_NOTE_9.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 33,
        title: "Redmi Note 11 Pro",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/08/15/41JZccrMnfL._SX300_SY300_QL70_ML2_.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 34,
        title: "Redmi Note 11T 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/redmi-note-11t-5g.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 35,
        title: "Redmi Note 11 Pro+ 5G",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/redmi-note-11-pro-5g.png",
        variant: "6GB/128GB",
    },
    {
        id: 36,
        title: "Redmi 9A",
        Brand: "Redmi",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/669632165.jpeg",
        variant: "6GB/128GB",
    },
];
/*******  -----  ONE PLUS -------      ********/
export const OnePlusMobiles = [{
        id: 1,
        title: "OnePlus 8",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_8.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 2,
        title: "OnePlus 7T Pro Mclaren Limited Edition",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_7T_PRO_MCLAREN_LIMITED_EDITION.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 3,
        title: "OnePlus 6",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-6.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 4,
        title: "OnePlus 6T Mclaren Limited Edition",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_6T_MCLAREN.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 5,
        title: "OnePlus 5",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-5.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 6,
        title: "OnePlus 5T",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-5t.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 7,
        title: "OnePlus 7 Pro",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_7_PRO.png",
        variant: "6GB/128GB",
    },
    {
        id: 8,
        title: "OnePlus 8T 5G",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_8T_5G.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 9,
        title: "OnePlus 8 Pro",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_8_PRO.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 10,
        title: "OnePlus 6T",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-6t.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 11,
        title: "OnePlus 9",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_9.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 12,
        title: "OnePlus 9R",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_9R.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 13,
        title: "OnePlus 7",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS7.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 14,
        title: "OnePlus 10R",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/09/716uVx3Wr5L._SL1500_.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 15,
        title: "OnePlus Nord CE 5G",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-nord-ce-5g.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 16,
        title: "OnePlus Nord CE 2 Lite 5G",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/08/31/71V--WZVUIL._SL1500_.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 17,
        title: "OnePlus Nord CE 2 5G",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-nord-ce-2.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 18,
        title: "OnePlus 9 Pro",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_9_PRO.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 19,
        title: "OnePlus Nord",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_NORD.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 20,
        title: "OnePlus 7T Pro",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_7T_PRO.png",
        variant: "6GB/128GB",
    },
    {
        id: 21,
        title: "OnePlus 7T",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/ONEPLUS_7T.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 22,
        title: "OnePlus Nord 2T 5G",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/25/61ahn9N38zL._SL1500_.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 23,
        title: "OnePlus 9RT",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-9rt.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 24,
        title: "OnePlus 10T",
        Brand: "One Plus",
        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/08/05/71XKAnxCsLL._AC_UY436_QL65_.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 25,
        title: "OnePlus 10 Pro",
        Brand: "One Plus",

        price: 40000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-10-pro.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 26,
        title: "OnePlus Nord 2 5G",
        Brand: "One Plus",

        price: 30000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/oneplus-nord-2.jpg",
        variant: "6GB/128GB",
    },
];
/******  -------- REAL ME ---------  ******/
export const RealMeMobiles = [{
        id: 1,
        title: "Realme 2",
        Brand: "Realme",

        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/REALME_2.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 2,
        title: "Realme 3",
        Brand: "Realme",
        desc: "",
        price: 25000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_3.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 3,
        title: "Realme 3 Pro",
        Brand: "Realme",
        desc: "",
        price: 23000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_3_PRO.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 4,
        title: "Realme 3i",
        Brand: "Realme",
        desc: "",
        price: 32000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_3I.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 5,
        title: "Realme 5",
        Brand: "Realme",
        desc: "",
        price: 22000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_5.jpeg",
        variant: "6GB/64GB",
    },
    {
        id: 6,
        title: "Realme 5 Pro",
        Brand: "Realme",
        desc: "",
        price: 16000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_5_PRO.jpeg",
        variant: "4GB/32GB",
    },
    {
        id: 7,
        title: "Realme 5s",
        Brand: "Realme",
        desc: "",
        price: 14000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_5S.jpeg",
        variant: "3GB/32GB",
    },
    {
        id: 8,
        title: "Realme 6",
        Brand: "Realme",
        desc: "",
        price: 17000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_6.jpeg",
        variant: "6GB/64GB",
    },
    {
        id: 9,
        title: "Realme 6 Pro",
        Brand: "Realme",
        desc: "",
        price: 15000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_6_PRO.jpeg",
        variant: "6GB/64GB",
    },
    {
        id: 10,
        title: "Realme 6i",
        Brand: "Realme",
        desc: "",
        price: 16000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_6I.jpeg",
        variant: "3GB/128GB",
    },
    {
        id: 11,
        title: "Realme 9 Pro 5G",
        Brand: "Realme",
        desc: "",
        price: 18000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_9_PRO_5G.jpeg",
        variant: "4GB/128GB",
    },
    {
        id: 12,
        title: "Realme C12",
        Brand: "Realme",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/29/REALME_C12.jpeg",
        variant: "6GB/128GB",
    },
];
/******* ------- OPP0 MOBILES -------------------- */
export const OPPOMobiles = [{
        id: 1,
        title: "Oppo A15",
        Brand: "OPPO",
        desc: "",
        price: 19000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A15.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 2,
        title: "Oppo A1K",
        Brand: "OPPO",
        desc: "",
        price: 21000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A1K.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 3,
        title: "Oppo A33 2020",
        Brand: "OPPO",
        desc: "",
        price: 18000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A33_2020.jpeg",
        variant: "6GB/64GB",
    },
    {
        id: 4,
        title: "Oppo A5",
        Brand: "OPPO",
        desc: "",
        price: 30000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A5.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 5,
        title: "Oppo A5 2020",
        Brand: "OPPO",
        desc: "",
        price: 17500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A5_2020.jpeg",
        variant: "3GB/32GB",
    },
    {
        id: 6,
        title: "Oppo A52",
        Brand: "OPPO",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A52.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 7,
        title: "Oppo A53",
        Brand: "OPPO",
        desc: "",
        price: 18000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A53.jpeg",
        variant: "4GB/32GB",
    },
    {
        id: 8,
        title: "Oppo A57",
        Brand: "OPPO",
        desc: "",
        price: 16000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A57.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 9,
        title: "Oppo A5S",
        Brand: "OPPO",
        desc: "",
        price: 21000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A5S.jpeg",
        variant: "4GB/128GB",
    },
    {
        id: 10,
        title: "Oppo A7",
        Brand: "OPPO",
        desc: "",
        price: 22000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A7.jpeg",
        variant: "6GB/32GB",
    },
    {
        id: 11,
        title: "Oppo A9",
        Brand: "OPPO",
        desc: "",
        price: 18500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A9.jpeg",
        variant: "6GB/64GB",
    },
    {
        id: 12,
        title: "Oppo A11K",
        Brand: "OPPO",
        desc: "",
        price: 25000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/OPPO_A11K.jpeg",
        variant: "6GB/128GB",
    },
];
/*******---------- POCO MOBILES --------------- */
export const PocoMobiles = [{
        id: 1,
        title: "Poco M2 Reloaded",
        Brand: "POCO",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/m2-reloaded-mzb0957in-poco-original-imag2aqyhdfvsty8.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 2,
        title: "Poco X2",
        Brand: "POCO",
        desc: "",
        price: 18000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/POCO_X2.jpeg",
        variant: "4GB/32GB",
    },
    {
        id: 3,
        title: "Poco X3",
        Brand: "POCO",
        desc: "",
        price: 17000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/POCO_X3.jpeg",
        variant: "6GB/64GB",
    },
    {
        id: 4,
        title: "Poco X3 Pro",
        Brand: "POCO",
        desc: "",
        price: 16900,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/x3-pro-mzb08t9in-poco-original-imag52znesm3hemf.jpeg",
        variant: "4GB/32GB",
    },
    {
        id: 5,
        title: "Poco C31",
        Brand: "POCO",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/51uX9vyZ7dL._SL1000_.jpg",
        variant: "4GB/64GB",
    },
    {
        id: 6,
        title: "Poco C3",
        Brand: "POCO",
        desc: "",
        price: 24000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/POCO_C3.jpeg",
        variant: "4GB/32GB",
    },
    {
        id: 7,
        title: "Poco X3 Pro",
        Brand: "POCO",
        desc: "",
        price: 17500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/x3-pro-mzb08t9in-poco-original-imag52znesm3hemf.jpeg",
        variant: "3GB/32GB",
    },
    {
        id: 8,
        title: "Poco F1",
        Brand: "POCO",
        desc: "",
        price: 18600,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/POCO_F1.jpeg",
        variant: "6GB/64GB",
    },
    {
        id: 9,
        title: "Poco M4 Pro 5G",
        Brand: "POCO",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/-original-imagcafj5zcxz9wg.jpeg",
        variant: "4GB/128GB",
    },
    {
        id: 10,
        title: "Poco M3",
        Brand: "POCO",
        desc: "",
        price: 22000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/m3-mzb087ain-poco-original-imafzxf8zqkcgwfv.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 11,
        title: "Poco M3 Pro 5G",
        Brand: "POCO",
        desc: "",
        price: 17500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/m3-pro-5g-mzb0952in-poco-original-imag3th6btkchjn2.jpeg",
        variant: "4GB/32GB",
    },
    {
        id: 12,
        title: "Poco M4 Pro",
        Brand: "POCO",
        desc: "",
        price: 18999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/-original-imagc7tduryuaynx.jpeg",
        variant: "3GB/64GB",
    },
    {
        id: 13,
        title: "Poco X4 Pro 5G",
        Brand: "POCO",
        desc: "",
        price: 22000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/-original-imagcv2dcyjzcmvd.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 14,
        title: "Poco F3 GT",
        Brand: "POCO",
        desc: "",
        price: 25000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/f3-gt-mzb09c5in-poco-original-imag57hetqwnqaac.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 15,
        title: "Poco M2 Pro",
        Brand: "POCO",
        desc: "",
        price: 19000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/POCO_M2_PRO.jpeg",
        variant: "6GB/128GB",
    },
];
/******** ---- IQOO MOBLES---- ********  */
export const IQOOMobiles = [{
        id: 1,
        title: "iQOO 7 5G",
        Brand: "IQOO",
        desc: "",
        price: 15000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_7_5G.jpg",
        variant: "6GB/64GB",
    },
    {
        id: 2,
        title: "iQOO Z3 5G",
        Brand: "IQOO",
        desc: "",
        price: 18000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_Z3_5G.jpg",
        variant: "4GB/32GB",
    },
    {
        id: 3,
        title: "iQOO Z6 5G",
        Brand: "IQOO",
        desc: "",
        price: 13500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_Z6_5G.jpg",
        variant: "4GB/32GB",
    },
    {
        id: 4,
        title: "iQOO Z6",
        Brand: "IQOO",
        desc: "",
        price: 14999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_Z6.jpg",
        variant: "3GB/32GB",
    },
    {
        id: 5,
        title: "iQOO Z6 Pro 5G",
        Brand: "IQOO",
        desc: "",
        price: 15999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_Z6_Pro_5G.jpg",
        variant: "3GB/32GB",
    },
    {
        id: 6,
        title: "iQOO 3",
        Brand: "IQOO",
        desc: "",
        price: 18999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_3.jpg",
        variant: "3GB/32GB",
    },
    {
        id: 7,
        title: "iQOO 9 SE 5G",
        Brand: "IQOO",
        desc: "",
        price: 17999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_9_SE_5G.jpg",
        variant: "4GB/64GB",
    },
    {
        id: 8,
        title: "iQOO 7 Legend 5G",
        Brand: "IQOO",
        desc: "",
        price: 20999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_7_Legend_5G.jpg",
        variant: "4GB/64GB",
    },
    {
        id: 9,
        title: "iQOO Neo 6 5G",
        Brand: "IQOO",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/09/06/71WS-0ITj7L._SL1200_.jpg",
        variant: "4GB/64GB",
    },
    {
        id: 10,
        title: "iQOO 9T 5G",
        Brand: "IQOO",
        desc: "",
        price: 15600,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/09/06/6157kraeaL._SL1200_.jpg",
        variant: "4GB/64GB",
    },
    {
        id: 11,
        title: "iQOO 9 5G",
        Brand: "IQOO",
        desc: "",
        price: 16000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_9_5G.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 12,
        title: "iQOO Z5 5G",
        Brand: "IQOO",
        desc: "",
        price: 19000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_Z5_5G.jpg",
        variant: "6GB/128GB",
    },
    {
        id: 13,
        title: "iQOO 9 Pro 5G",
        Brand: "IQOO",
        desc: "",
        price: "",
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/06/30/iQOO_9_Pro_5G.jpg",
        variant: "6GB/128GB",
    },
];
/******** ---- VIVO MOBLES---- ********  */
export const VIVOMobiles = [{
        id: 1,
        title: "Vivo S1",
        Brand: "VIVO",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_S1.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 2,
        title: "Vivo S1 Pro",
        Brand: "VIVO",
        desc: "",
        price: 18000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_S1_PRO.jpeg",
        variant: "4GB/128GB",
    },
    {
        id: 3,
        title: "Vivo U10",
        Brand: "VIVO",
        desc: "",
        price: 22000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_U10.jpeg",
        variant: "4GB/32GB",
    },
    {
        id: 4,
        title: "Vivo U20",
        Brand: "VIVO",
        desc: "",
        price: 16000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_U20.jpeg",
        variant: "6GB/128GB",
    },
    {
        id: 5,
        title: "Vivo V11",
        Brand: "VIVO",
        desc: "",
        price: 23000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_V11.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 6,
        title: "Vivo V11 Pro",
        Brand: "VIVO",
        desc: "",
        price: 10000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_V11_PRO.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 7,
        title: "Vivo V15",
        Brand: "VIVO",
        desc: "",
        price: 13500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_V15.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 8,
        title: "Vivo V15 Pro",
        Brand: "VIVO",
        desc: "",
        price: 14500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_V15_PRO.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 9,
        title: "Vivo V20 Pro",
        Brand: "VIVO",
        desc: "",
        price: 15999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_V20_PRO.jpeg",
        variant: "3GB/32GB",
    },
    {
        id: 10,
        title: "Vivo V20 SE",
        Brand: "VIVO",
        desc: "",
        price: 18999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_V20_SE.jpeg",
        variant: "3GB/32GB",
    },
    {
        id: 11,
        title: "Vivo V21E 5G",
        Brand: "VIVO",
        desc: "",
        price: 20999,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/vivo-v21e-5g.jpeg",
        variant: "3GB/32GB",
    },
    {
        id: 12,
        title: "Vivo V7",
        Brand: "VIVO",
        desc: "",
        price: 12600,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/28/VIVO_V7.jpeg",
        variant: "3GB/32GB",
    },
];
/******** ---- APPLE MOBLES---- ********  */

export const AppleMobiles = [{
        id: 1,
        title: "iPhone 6S",
        Brand: "Apple",
        desc: "",
        price: 55000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/6S.jpeg",
        variant: "128GB",
    },
    {
        id: 2,
        title: "iPhone 6S Plus",
        Brand: "Apple",
        desc: "",
        price: 43000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/6SPLUS.jpeg",
        variant: "64GB",
    },
    {
        id: 3,
        title: "iPhone 6 Plus",
        Brand: "Apple",
        desc: "",
        price: 36000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/6PLUS.jpeg",
        variant: "32GB",
    },
    {
        id: 4,
        title: "iPhone SE 2020",
        Brand: "Apple",
        desc: "",
        price: 35000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/10/01/apple-iphone-se-mxd02hn-a-original-imafrcpjyscxm8fv.jpeg",
        variant: "128GB",
    },
    {
        id: 5,
        title: "iPhone 7",
        Brand: "Apple",
        desc: "",
        price: 28000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/7.jpeg",
        variant: "64GB",
    },
    {
        id: 6,
        title: "iPhone 7 Plus",
        Brand: "Apple",
        desc: "",
        price: 42000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/7PLUS.jpeg",
        variant: "64GB",
    },
    {
        id: 7,
        title: "iPhone 8",
        Brand: "Apple",
        desc: "",
        price: 38000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/8.jpeg",
        variant: "64GB",
    },
    {
        id: 8,
        title: "iPhone 8 Plus",
        Brand: "Apple",
        desc: "",
        price: 35000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/8PLUS.jpeg",
        variant: "64GB",
    },
    {
        id: 9,
        title: "iPhone SE3 2022",
        Brand: "Apple",
        desc: "",
        price: 50000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/apple-iphone-se-2022-iphone-se3.jpg",
        variant: "128GB",
    },
    {
        id: 10,
        title: "iPhone 11 Pro",
        Brand: "Apple",
        desc: "",
        price: 40000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/11PRO.jpeg",
        variant: "64GB",
    },
    {
        id: 11,
        title: "iPhone XS",
        Brand: "Apple",
        desc: "",
        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/XS.jpeg",
        variant: "32GB",
    },
    {
        id: 12,
        title: "iPhone XS Max",
        Brand: "Apple",
        desc: "",
        price: 8500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/26/XSMAX.jpeg",
        variant: "16GB",
    },
];
/*** NOTHING MOBLES */
export const NothingMobiles = [{
    id: 1,
    title: "Nothing Phone 1",
    Brand: "Nothing",
    desc: "",
    price: 23000,
    img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/09/14/-original-imagg4xza5rehdqv.jpeg",
    variant: "8GB/128GB",
}, ];

/********-------  TABLETS  -----------********/

/***************--------  APPLE TABLETS  -----------***************/
export const AppleTablets = [{
        id: 1,
        title: "iPad 10.2 7Th Generation Wi-Fi (2019)",
        Brand: "Apple",
        desc: "",
        price: 11500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_10.2_7TH_GENERATION_WI-FI_2019.jpeg",
        variant: "32GB",
    },
    {
        id: 2,
        title: "iPad 7Th Generation Wi-Fi + Cellular (2019)",
        Brand: "Apple",
        desc: "",
        price: 10000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_7TH_GENERATION_WI-FI__CELLULAR_2019.jpeg",
        variant: "32GB",
    },
    {
        id: 3,
        title: "iPad 8Th Generation Cellular + Wi-Fi (2020)",
        Brand: "Apple",
        desc: "",
        price: 8500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_8TH_GENERATION_CELLULAR__WI-FI.jpeg",
        variant: "32GB",
    },
    {
        id: 4,
        title: "iPad 8Th Generation Wi-Fi Only",
        Brand: "Apple",
        desc: "",
        price: 4500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_8TH_GENERATION_WI-FI_ONLY.jpeg",
        variant: "20GB",
    },
    {
        id: 5,
        title: "iPad 9.7 5Th Generation Wi-Fi + Cellular (2017)",
        Brand: "Apple",
        desc: "",
        price: 4500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_9.7_5TH_GENERATION_WI-FI__CELLULAR_2017.jpeg",
        variant: "16GB",
    },
    {
        id: 6,
        title: "iPad 9.7 5Th Generation Wi-Fi (2017)",
        Brand: "Apple",
        desc: "",
        price: 7600,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_9.7_5TH_GENERATION_WI-FI_2017.jpeg",
        variant: "12GB",
    },
    {
        id: 7,
        title: "iPad 9.7 6Th Generation Wi-Fi (2018)",
        Brand: "Apple",
        desc: "",
        price: 3000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_9.7_6TH_GENERATION_WI-FI_2018.jpeg",
        variant: "8GB",
    },
    {
        id: 8,
        title: "iPad 9.7 6Th Generation Wi-Fi + Cellular (2018)",
        Brand: "Apple",
        desc: "",
        price: 4500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_9.7_6TH_GENERATION_WI-FI__CELLULAR_2018.jpeg",
        variant: "28GB",
    },
    {
        id: 9,
        title: "iPad Air 2 Wi-Fi",
        Brand: "Apple",
        desc: "",
        price: 5500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_AIR_2_WI-FI.jpg",
        variant: "24GB",
    },
    {
        id: 10,
        title: "iPad Air With Wi-Fi + Cellular ( Retina Display )",
        Brand: "Apple",
        desc: "",
        price: 6900,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_AIR_WITH_WI-FI__CELLULAR__RETINA_DISPLAY_.jpeg",
        variant: "12GB",
    },
    {
        id: 11,
        title: "iPad Mini 4 Wi-Fi",
        Brand: "Apple",
        desc: "",
        price: 5500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_MINI_4_WI-FI.jpeg",
        variant: "16GB",
    },
    {
        id: 12,
        title: "iPad Mini 4 Wi-Fi + Cellular",
        Brand: "Apple",
        desc: "",
        price: 6000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/IPAD_MINI_4_WI-FI__CELLULAR.jpeg",
        variant: "32GB",
    },
];
/**************       SAMSUNG     ******************* */
export const SamsungTablets = [{
        id: 1,
        title: "Galaxy Tab S7 Plus 12.4 LTE",
        Brand: "Samsung",
        desc: "",
        price: 7800,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_S7_PLUS_12.4_LTE.jpg",
        variant: "16GB",
    },
    {
        id: 2,
        title: "Galaxy Tab S7 Wi-Fi",
        Brand: "Samsung",
        desc: "",
        price: 6500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_S7_11_WI-FI.jpg",
        variant: "12GB",
    },
    {
        id: 3,
        title: "Galaxy Tab S7 LTE",
        Brand: "Samsung",
        desc: "",
        price: 10500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_S7_11_LTE.jpg",
        variant: "32GB",
    },
    {
        id: 4,
        title: "Galaxy Tab A 10.1 Lte (2019)",
        Brand: "Samsung",
        desc: "",
        price: 8000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_A_10.1_LTE_2019.jpg",
        variant: "28GB",
    },
    {
        id: 5,
        title: "Galaxy Tab A 10.1 Wi-Fi (2019)",
        Brand: "Samsung",
        desc: "",
        price: 10000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_A_10.1_WI-FI_2019.jpg",
        variant: "28GB",
    },
    {
        id: 6,
        title: "Galaxy Tab A 10.5 Lte (2018)",
        Brand: "Samsung",
        desc: "",
        price: 13000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_A_10.5_LTE_2018.jpg",
        variant: "24GB",
    },
    {
        id: 7,
        title: "Galaxy Tab A 8.0 Lte (2017)",
        Brand: "Samsung",
        desc: "",
        price: 11000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_A_8.0_LTE_2017.jpg",
        variant: "20GB",
    },
    {
        id: 8,
        title: "Galaxy Tab A 8.0 Wi-Fi (2019)",
        Brand: "Samsung",
        desc: "",
        price: 9000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_A_8.0_WI-FI_2019.jpg",
        variant: "16GB",
    },
    {
        id: 9,
        title: "Galaxy Tab A 9.7 Wi-Fi",
        Brand: "Samsung",
        desc: "",
        price: 7000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_A_9.7_WI-FI.jpg",
        variant: "12GB",
    },
    {
        id: 10,
        title: "Galaxy Tab S 10.5 LTE",
        Brand: "Samsung",
        desc: "",
        price: 5000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_S_10.5_LTE.jpg",
        variant: "8GB",
    },
    {
        id: 11,
        title: "Galaxy Tab S 8.4 Lte",
        Brand: "Samsung",
        desc: "",
        price: 8000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_S_8.4_LTE.jpeg",
        variant: "16GB",
    },
    {
        id: 12,
        title: "Galaxy Tab S 8.4 Wi-Fi",
        Brand: "Samsung",
        desc: "",
        price: 12000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/04/30/GALAXY_TAB_S_8.4_WI-FI.jpeg",
        variant: "32GB",
    },
];
/****---------- LENOVO  ------------*** */
export const LenovoTablets = [{
        id: 1,
        title: "Yoga Tab 3 Pro Wi-Fi + 4G",
        Brand: "Lenovo",
        desc: "",
        price: 9500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/YOGA_TAB_3_PRO_WI-FI__4G.jpg",
        variant: "24GB",
    },
    {
        id: 2,
        title: "Yoga Smart Tab Wi-Fi + 4G",
        Brand: "Lenovo",
        desc: "",
        price: 7500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/YOGA_SMART_TAB_WI-FI__4G.jpg",
        variant: "12GB",
    },
];

/**********----- Real Me Tablets ----------*************** */
export const RealmeTablets = [{
        id: 1,
        title: "Realme Pad Mini LTE",
        Brand: "Realme",
        desc: "",
        price: 6000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/14/41eEke04TVL.jpg",
        variant: "4GB",
    },
    {
        id: 2,
        title: "Realme Pad Wi-Fi Only",
        Brand: "Realme",
        desc: "",
        price: 7500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/14/41eEke04TVL.jpg",
        variant: "32GB",
    },
    {
        id: 3,
        title: "Realme Pad LTE",
        Brand: "Realme",
        desc: "",
        price: 5500,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/14/41eEke04TVL.jpg",
        variant: "8GB",
    },
    {
        id: 4,
        title: "Realme Pad Mini Wi-Fi Only",
        Brand: "Realme",
        desc: "",
        price: 8000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/14/41eEke04TVL.jpg",
        variant: "16GB",
    },
];
/**********----MI TABLETS--------******** */

export const MiTablets = [{
    id: 1,
    title: "XIAOMI PAD 5 Wi-Fi Only",
    Brand: "Redmi",
    desc: "",
    price: 10500,
    img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/07/14/61Eb9vtdSML._SL1500_.jpg",
    variant: "32GB",
}, ];
/******------LAPTOP------******* */
/********------APPLE------************ */
export const AppleLaptop = [{
    id: 1,
    title: "iMac With Retina",
    Brand: "Apple",
    desc: "",
    price: 90000,
    img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/IMAC_WITH_RETINA.jpg",
    variant: "8GB/256GB",
}, ];

/********------hp laptop------************ */
export const HpLaptop = [{
    id: 1,
    title: "Hp 15S Core I5",
    Brand: "HP",
    desc: "",
    price: 80000,
    img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/HP_15S_CORE_I5.jpeg",
    variant: "8GB/512GB",
}, ];
/********------ACCER LAPTOP------************ */
export const AcerLaptop = [{
        id: 1,
        title: "Acer One 14 Pentium Dual Core",
        Brand: "Acer",
        desc: "",
        price: 38000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/ACER_ONE_14_PENTIUM_DUAL_CORE.jpeg",
        variant: "4GB/64GB",
    },
    {
        id: 2,
        title: "Acer Aspire 7",
        Brand: "Acer",
        desc: "",
        price: 70000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/ACER_ASPIRE_7.jpeg",
        variant: "6GB/256GB",
    },
];
/******---Asus -----******* */

export const AsusLaptop = [{
        id: 1,
        title: "Asus Vivobook 14",
        Brand: "Asus",
        desc: "",
        price: 43000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/ASUS_VIVOBOOK_14.jpeg",
        variant: "3GB/64GB",
    },
    {
        id: 2,
        title: "Asus Vivobook 15",
        Brand: "Asus",
        desc: "",
        price: 52000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/ASUS_VIVOBOOK_15.jpeg",
        variant: "4GB/128GB",
    },
];
/*********-----Delll----********* */
export const DellLaptop = [{
    id: 1,
    title: "Dell Inspiron Apu",
    Brand: "Dell",
    desc: "",
    price: 45000,
    img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/05/01/DELL_INSPIRON_APU.jpeg",
    variant: "8GB/512GB",
}, ];
/*****Lenovo, MI,REALME,MSI,MICROSOFT nothing** */




/*******---APPLE Watch-----****** */
export const AppleWatch = [{
        id: 1,
        title: "Apple Watch Series 8 Aluminum (GPS+Cellular)",
        Brand: "Apple",

        price: 90000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/71OylAZAe2L._SL1500_.jpg",
        variant: 40,
    },
    {
        id: 2,
        title: "Apple Watch Series 7 Titanium (GPS+Cellular)",
        Brand: "Apple",

        price: 50000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/mxw_2256s_jp2s_videoimgns_atwebpf_auto.png",
        variant: 42,
    },
    {
        id: 3,
        title: "Apple Watch Series 7 Aluminium (GPS Only)",
        Brand: "Apple",
        desc: "",
        price: 60000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/ios-mkhu3hn-a-apple-yes-original-imag7eqy5axn6hpg.jpeg",
        variant: 45,
    },
    {
        id: 4,
        title: "Apple Watch Series 7 Stainless Steel (GPS+Cellular)",
        Brand: "Apple",

        price: 56000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/ios-mkj03hn-a-apple-yes-original-imag7eqyff4ryyuw.jpeg",
        variant: 40,
    },
    {
        id: 5,
        title: "Apple Watch Series 7 Aluminium (GPS+Cellular)",
        Brand: "Apple",
        price: 73000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/ios-mkhu3hn-a-apple-yes-original-imag7eqy5axn6hpg.jpeg",
        variant: 35,
    },
    {
        id: 6,
        title: "Apple Watch Ultra 49mm GPS+Cellular",
        Brand: "Apple",

        price: 100000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/12/Apple_Watch_Ultra_49mm_GPSCellular.jpg",
        variant: 42,
    },
    {
        id: 7,
        title: "Apple Watch Series 8 Stainless Steel (GPS+ Cellular)",
        Brand: "Apple",

        price: 58000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/91DRCHFCw0L._SL1500_.jpg",
        variant: 42,
    },
    {
        id: 8,
        title: "Apple Watch Series 8 Aluminum (GPS Only)",
        Brand: "Apple",

        price: 20000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/71OylAZAe2L._SL1500_.jpg",
        variant: 38,
    },
    {
        id: 9,
        title: "Apple Watch SE (2022) GPS+Cellular",
        Brand: "Apple",
        price: 30000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/71lG7br7k1L._SL1500_.jpg",
        variant: 45,
    },
    {
        id: 10,
        title: "Apple Watch SE (2022) GPS Only",
        Brand: "Apple",
        price: 80000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/71lG7br7k1L._SL1500_.jpg",
        variant: 45,
    },
    {
        id: 11,
        title: "Apple Watch SE (GPS+Cellular)",
        Brand: "Apple",
        price: 75000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/71lU6IcsUcL._SL1500_.jpg",
        variant: 45,
    },
    {
        id: 12,
        title: "Apple Watch SE (GPS Only)",
        Brand: "Apple",
        price: 50000,
        img: "https://buybackart-s3-prod-bucket.s3.amazonaws.com/static/products/2022/11/13/71lU6IcsUcL._SL1500_.jpg",
        variant: 41,
    },
];